version: '3.1'

services:

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db_worker:
    build: app/

    depends_on:
      - db
  api:
    build: app/

    depends_on:
      - db_worker
    ports:
      - 8000:8000


